// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// <!--@An experimental API that allows extensions to inject suggest links in the recommended pane of the New Tab Page.-->
// 允许扩展程序在“打开新的标签页”页面中的推荐窗格中插入推荐的链接的实验性 API。
namespace experimental.discovery {

  dictionary SuggestDetails {
    // <!--@The URL to suggest and that will be displayed in the new tab page under
    // the recommended pane.-->
    // 要推荐的 URL，它将显示在“打开新的标签页”页面的推荐窗格中。
    DOMString linkUrl;

    // <!--@The linkified text. It should be relatively short.-->
    // 链接文字，应该相对较短。
    DOMString linkText;

    // <!--@The url of the image to use as a tile.-->
    // 用于缩略图的图片 URL。
    DOMString? urlImage;

    // <!--@A score indicating how interesting that suggestion is. The value must be
    // between 0 and 1. A suggestion with score 1 is twice as likely to be
    // displayed than one with a score of 0.5. Defaults to 1.-->
    // 表示推荐的内容吸引用户程度的评分，该值必须在 0 和 1 之间。评分为 1
    // 的建议显示出来的可能性是评分为 0.5 的建议的两倍。默认为 1。
    // <!--@TODO: need minimum=0 and maximum=1.-->
    double? score;
  };

  interface Functions {
    // <!--@Suggests a URL for discovery.-->
    // 推荐 URL。
    // |details|: <!--@Detailed information on the URL to suggest.-->
    // 要推荐给发现服务 URL 的详情。
    static void suggest(SuggestDetails details);

    // <!--@Removes a URL that was previously suggested for discovery by this
    // extension.-->
    // 移除当前扩展程序之前推荐给发现服务的某个 URL。
    // |linkUrl|: <!--@The URl to remove from discovery. Must be exactly the same as
    // a linkUrl previously used on a call to suggest.-->
    // 要从发现服务中移除的 URI，必须跟之前传递给 suggest 方法的某个
    // linkUrl 完全相同。
    static void removeSuggestion(DOMString linkUrl);

    // <!--@Clear all the URLs that were previously suggested for discovery by this
    // extension.-->
    // 清除当前扩展程序以前推荐给发现服务的所有 URL。
    static void clearAllSuggestions();
  };
};
