// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// File-level comment to appease parser. Eventually this will not be necessary.
namespace systemInfo.cpu {

  dictionary CpuInfo {
    // <!--@The number of logical processors.-->
    // 逻辑处理器数目。
    long numOfProcessors;
    // <!--@The architecture name of the processors.-->
    // 处理器的架构名称。
    DOMString archName;
    // <!--@The model name of the processors.-->
    // 处理器的模型名称。
    DOMString modelName;
  };

  callback CpuInfoCallback = void (CpuInfo info);
  
  interface Functions {
    // <!--@Queries basic CPU information of the system.-->
    // 查询系统 CPU 的基本信息。
    static void get(CpuInfoCallback callback);
  };
};
