// Copyright 2013 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// File-level comment to appease parser. Eventually this will not be necessary.
namespace systemInfo.memory {

  dictionary MemoryInfo {
    // <!--@The total amount of physical memory capacity, in bytes.-->
    // 物理内存容量的总计大小，以字节为单位。
    double capacity;
    // <!--@The amount of available capacity, in bytes.-->
    // 可用容量的大小，以字节为单位。
    double availableCapacity;
  };

  callback MemoryInfoCallback = void (MemoryInfo info);
  
  interface Functions {
    // <!--@Get physical memory information.-->
    // 获取物理内存信息。
    static void get(MemoryInfoCallback callback);
  };
};
