// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// <!--@Use the <code>chrome.app.window</code> API to create windows. Windows
// have an optional frame with title bar and size controls. They are not
// associated with any Chrome browser windows.-->
// 使用 <code>chrome.app.window</code> API
// 创建窗口。窗口可以有框架，包含标题栏和大小控件，它们不和任何
// Chrome 浏览器窗口关联。
namespace app.window {

  // <!--@Previously named Bounds.-->
  // 原来叫做 Bounds。
  dictionary ContentBounds {
    long? left;
    long? top;
    long? width;
    long? height;
  };

  dictionary BoundsSpecification {
    // The X coordinate of the content or window.
    long? left;

    // The Y coordinate of the content or window.
    long? top;

    // The width of the content or window.
    long? width;

    // The height of the content or window.
    long? height;

    // The minimum width of the content or window.
    long? minWidth;

    // The minimum height of the content or window.
    long? minHeight;

    // The maximum width of the content or window.
    long? maxWidth;

    // The maximum height of the content or window.
    long? maxHeight;
  };

  dictionary Bounds {
    // <!--@The current X coordinate of the content or window.-->
    // 内容或窗口当前的 X 坐标。
    long left;

    // <!--@The current Y coordinate of the content or window.-->
    // 内容或窗口当前的 Y 坐标。
    long top;

    // <!--@The current width of the content or window.-->
    // 内容或窗口的当前宽度。
    long width;

    // <!--@The current height of the content or window.-->
    // 内容或窗口的当前高度。
    long height;

    // <!--@The current minimum width of the content or window.
    // Will be <code>null</code> if not specified.-->
    // 内容或窗口当前的最小宽度，如果没有指定则为 <code>null</code>。
    long? minWidth;

    // <!--@The current minimum height of the content or window.
    // Will be <code>null</code> if not specified.-->
    // 内容或窗口当前的最小高度，如果没有指定则为 <code>null</code>。
    long? minHeight;

    // <!--@The current maximum width of the content or window.
    // Will be <code>null</code> if not specified.-->
    // 内容或窗口当前的最大宽度，如果没有指定则为 <code>null</code>。
    long? maxWidth;

    // <!--@The current maximum height of the content or window.
    // Will be <code>null</code> if not specified.-->
    // 内容或窗口当前的最大高度，如果没有指定则为 <code>null</code>。
    long? maxHeight;
  };

  // TODO(benwells): document this once we are happy with it.
  [nodoc] dictionary FrameOptions {
    DOMString? type;
    DOMString? color;
  };

  // <!--@State of a window: normal, fullscreen, maximized, minimized.-->
  // 窗口的状态：正常、全屏、最大化、最小化。
  enum State { normal, fullscreen, maximized, minimized };

  // 'shell' is the default window type. 'panel' is managed by the OS
  // (Currently experimental, Ash only).
  [nodoc] enum WindowType { shell, panel };

  dictionary CreateWindowOptions {
    // <!--@Id to identify the window. This will be used to remember the size
    // and position of the window and restore that geometry when a window
    // with the same id is later opened.
    // If a window with a given id is created while another window with the same
    // id already exists, the currently opened window will be focused instead of
    // creating a new window.-->
    // 用于标识窗口的标识符，会用来记住窗口的大小与位置，当同一标识符的窗口再次打开时恢复原来的尺寸。如果创建窗口时另一个具有同样标识符的窗口已经存在，当前打开的窗口将获得焦点，而不会创建新窗口。
    DOMString? id;

    // <!--@Used to specify the initial position, initial size and constraints of the
    // window's content (excluding window decorations).
    // If an <code>id</code> is also specified and a window with a matching
    // <code>id</code> has been shown before, the remembered bounds will be used
    // instead.-->
    // 用于指定窗口内容（不包括窗口装饰部分）的初始位置、初始大小和约束。如果还指定了
    // <code>id</code> 并且之前显示过匹配 <code>id</code>
    // 的窗口，则使用记录下来的位置和大小。
    //
    // <!--@Note that the padding between the inner and outer bounds is determined by
    // the OS. Therefore setting the same bounds property for both the
    // <code>innerBounds</code> and <code>outerBounds</code> will result in an
    // error.-->
    // 注意，窗口内外边框之间的距离由操作系统决定，所以
    // <code>innerBounds</code> 和 <code>outerBounds</code>
    // 设置同样的属性值会导致错误。
    //
    // <!--@Currently only available on the Dev channel from Chrome 35.-->
    // 目前仅在 Chrome 35 或更高版本的 Dev 分支中可用。
    BoundsSpecification? innerBounds;

    // <!--@Used to specify the initial position, initial size and constraints of the
    // window (including window decorations such as the title bar and frame).
    // If an <code>id</code> is also specified and a window with a matching
    // <code>id</code> has been shown before, the remembered bounds will be used
    // instead.-->
    // 用于指定窗口（包括窗口装饰部分，如标题栏和边框）的初始位置、初始大小和约束。如果还指定了
    // <code>id</code> 并且之前显示过匹配 <code>id</code>
    // 的窗口，则使用记录下来的位置和大小。
    //
    // <!--@Note that the padding between the inner and outer bounds is determined by
    // the OS. Therefore setting the same bounds property for both the
    // <code>innerBounds</code> and <code>outerBounds</code> will result in an
    // error.-->
    // 注意，窗口内外边框之间的距离由操作系统决定，所以
    // <code>innerBounds</code> 和 <code>outerBounds</code>
    // 设置同样的属性值会导致错误。
    //
    // <!--@Currently only available on the Dev channel from Chrome 35.-->
    // 目前仅在 Chrome 35 或更高版本的 Dev 分支中可用。
    BoundsSpecification? outerBounds;

    // Default width of the window.
    [nodoc, deprecated="请使用 $ref:BoundsSpecification。"] long? defaultWidth;

    // Default height of the window.
    [nodoc, deprecated="请使用 $ref:BoundsSpecification。"] long? defaultHeight;

    // Default X coordinate of the window.
    [nodoc, deprecated="请使用 $ref:BoundsSpecification。"] long? defaultLeft;

    // Default Y coordinate of the window.
    [nodoc, deprecated="请使用 $ref:BoundsSpecification。"] long? defaultTop;

    // Width of the window.
    [nodoc, deprecated="请使用 $ref:BoundsSpecification。"] long? width;

    // Height of the window.
    [nodoc, deprecated="请使用 $ref:BoundsSpecification。"] long? height;

    // X coordinate of the window.
    [nodoc, deprecated="请使用 $ref:BoundsSpecification。"] long? left;

    // Y coordinate of the window.
    [nodoc, deprecated="请使用 $ref:BoundsSpecification。"] long? top;

    // <!--@Minimum width of the window.-->
    // 窗口的最小宽度。
    long? minWidth;

    // <!--@Minimum height of the window.-->
    // 窗口的最小高度。
    long? minHeight;

    // <!--@Maximum width of the window.-->
    // 窗口的最大宽度。
    long? maxWidth;

    // <!--@Maximum height of the window.-->
    // 窗口的最大高度。
    long? maxHeight;

    // Type of window to create.
    [nodoc] WindowType? type;

    // <!--@Frame type: <code>none</code> or <code>chrome</code> (defaults to
    // <code>chrome</code>). For <code>none</code>, the
    // <code>-webkit-app-region</code> CSS property can be used to apply
    // draggability to the app's window. <code>-webkit-app-region: drag</code>
    // can be used to mark regions draggable. <code>no-drag</code> can be used
    // to disable this style on nested elements.-->
    // 框架类型：'none' 或 'chrome'（默认为 'chrome'）。如果使用
    // 'none'，可以通过 CSS 属性 <code>-webkit-app-region</code>
    // 设置应用窗口的拖放特性。<code>-webkit-app-region: drag</code>
    // 可以将区域标志为可拖放的，而 <code>no-drag</code>
    // 可以用来在嵌套元素上禁用该样式。
    DOMString? frame;

    // TODO(benwells): Fix the IDL parsing so this can be:
    // (DOMString or FrameOptions)? frame.
    [nodoc] FrameOptions? frameOptions;

    // <!--@Size and position of the content in the window (excluding the titlebar).
    // If an id is also specified and a window with a matching id has been shown
    // before, the remembered bounds of the window will be used instead.-->
    // 窗口中内容的大小与位置（不包括标题栏）。如果同时指定了
    // id，并且以前显示过匹配标识符的窗口，则会使用记录下来的窗口大小与位置。
    ContentBounds? bounds;

    // <!--@Enable window background transparency.
    // Only supported in ash. Requires experimental API permission.-->
    // 启用窗口背景透明，仅在 ash 中支持，需要实验性 API 权限。
    boolean? transparentBackground;

    // <!--@The initial state of the window, allowing it to be created already
    // fullscreen, maximized, or minimized. Defaults to 'normal'.-->
    // 窗口的初始状态，允许使它在创建时就全屏、最大化或最小化。默认为
    // 'normal'（正常）。
    State? state;

    // <!--@If true, the window will be created in a hidden state. Call show() on
    // the window to show it once it has been created. Defaults to false.-->
    // 如果为 true，该窗口创建后将处于隐藏状态，创建之后在该窗口上调用
    // show() 可以显示它。默认为 false。
    boolean? hidden;

    // <!--@If true, the window will be resizable by the user. Defaults to true.-->
    // 如果为 true 的话，用户可以调整窗口的大小。默认为 true。
    boolean? resizable;

    // <!--@By default if you specify an id for the window, the window will only be
    // created if another window with the same id doesn't already exist. If a
    // window with the same id already exists that window is activated instead.
    // If you do want to create multiple windows with the same id, you can
    // set this property to false.-->
    // 默认情况下，如果您指定了窗口的标识符，只有当另一个具有相同标识符的窗口不存在时才会创建。如果另一个具有相同标识符的窗口存在，则它将变为活动窗口。如果您确实需要创建多个相同标识符的窗口，您可以将该属性设置为
    // false。
    [deprecated="<!--@Multiple windows with the same id is no longer supported.-->不再支持具有相同标志的多个窗口。"] boolean? singleton;

    // <!--@If true, the window will stay above most other windows. If there are
    // multiple windows of this kind, the currently focused window will be in
    // the foreground. Requires the <code>"alwaysOnTopWindows"</code>
    // permission. Defaults to false.<br>
    // Call <code>setAlwaysOnTop()</code> on the window to change this property
    // after creation.<br>-->
    // 如果为
    // true，窗口会保持在其他大部分窗口之上。如果有多个这样的窗口，当前具有焦点的窗口会在前台。需要
    // <code>"alwaysOnTopWindows"</code> 权限，默认为 false。创建窗口后调用
    // <code>setAlwaysOnTop</code> 修改该属性。
    boolean? alwaysOnTop;

    // <!--@If true, the window will be focused when created. Defaults to true.-->
    // 如果为 true，窗口创建时具有焦点。默认为 true。
    boolean? focused;
  };

  // <!--@Called in the creating window (parent) before the load event is called in
  // the created window (child). The parent can set fields or functions on the
  // child usable from onload. E.g. background.js:<br>
  // <code>function(createdWindow) { createdWindow.contentWindow.foo =
  // function () { }; };</code>
  // <br>window.js:<br>
  // <code>window.onload = function () { foo(); }</code>-->
  // 在已创建窗口（子窗口）的 load
  // 事件产生前在父窗口中调用，父窗口可以设置子窗口中的字段或函数，以便在
  // onload 中使用。例如：background.js：<br>
  // <code>function(createdWindow) { createdWindow.contentWindow.foo =
  // function () { }; };</code>
  // <br>window.js：<br>
  // <code>window.onload = function () { foo(); }</code>
  callback CreateWindowCallback =
      void ([instanceOf=AppWindow] object createdWindow);

  [noinline_doc] dictionary AppWindow {
    // <!--@Focus the window.-->
    // 使窗口拥有焦点。
    static void focus();

    // <!--@Fullscreens the window.<br>
    // The user will be able to restore the window by pressing ESC. An
    // application can prevent the fullscreen state to be left when ESC is
    // pressed by requesting the <b>overrideEscFullscreen</b> permission and
    // canceling the event by calling .preventDefault(), like this:<br>-->
    // 使窗口进入全屏状态。<br>
    // 用户可以按下 Esc 键恢复窗口。如果应用请求 <b>overrideEscFullscreen</b>
    // 权限，并调用 .preventDefault()
    // 取消事件，就能避免离开全屏状态，如下所示：<br>
    // <code>window.onKeyDown = function(e) { if (e.keyCode == 27 /* ESC */) {
    // e.preventDefault(); } };</code>
    static void fullscreen();

    // <!--@Is the window fullscreen?-->
    // 窗口是否处于全屏状态。
    static boolean isFullscreen();

    // <!--@Minimize the window.-->
    // 最小化窗口。
    static void minimize();

    // <!--@Is the window minimized?-->
    // 窗口是否最小化。
    static boolean isMinimized();

    // <!--@Maximize the window.-->
    // 最大化窗口。
    static void maximize();

    // <!--@Is the window maximized?-->
    // 窗口是否最大化。
    static boolean isMaximized();

    // <!--@Restore the window, exiting a maximized, minimized, or fullscreen state.-->
    // 从最大化、最小化或全屏状态恢复窗口。
    static void restore();

    // <!--@Move the window to the position (|left|, |top|).-->
    // 将窗口移到指定位置（<code>left</code>、<code>top</code>）。
    static void moveTo(long left, long top);

    // <!--@Resize the window to |width|x|height| pixels in size.-->
    // 将窗口大小调整为 <code>width</code> × <code>height</code> 像素。
    static void resizeTo(long width, long height);

    // <!--@Draw attention to the window.-->
    // 吸引用户注意该窗口。
    static void drawAttention();

    // <!--@Clear attention to the window.-->
    // 取消对窗口的吸引。
    static void clearAttention();

    // <!--@Close the window.-->
    // 关闭窗口。
    static void close();

    // <!--@Show the window. Does nothing if the window is already visible.
    // Focus the window if |focused| is set to true or omitted.-->
    // 显示窗口，如果窗口已经可见则什么都不做。如果 <code>focused</code>
    // 设置为 true 或省略则使窗口获得焦点。
    static void show(optional boolean focused);

    // <!--@Hide the window. Does nothing if the window is already hidden.-->
    // 隐藏窗口，如果窗口已经可见则什么都不做。
    static void hide();

    // <!--@Get the window's inner bounds as a $ref:ContentBounds object.-->
    // 获取窗口内部的大小与位置，以 $ref:ContentBounds 对象表示。
    [nocompile] static ContentBounds getBounds();

    // <!--@Set the window's inner bounds.-->
    // 设置窗口内部的大小与位置。
    static void setBounds(ContentBounds bounds);

    // <!--@Get the current minimum width of the window. Returns <code>null</code> if
    // there is no minimum. Currently only available on the Dev channel.-->
    // 获取窗口当前的最小宽度，如果没有最小值则返回 <code>null</code>。目前仅在 Dev 分支中可用。
    [nocompile] static long getMinWidth();

    // <!--@Get the current minimum height of the window. Returns <code>null</code>
    // if there is no minimum. Currently only available on the Dev channel.-->
    // 获取窗口当前的最小高度，如果没有最小值则返回 <code>null</code>。目前仅在 Dev 分支中可用。
    [nocompile] static long getMinHeight();

    // <!--@Get the current maximum width of the window. Returns <code>null</code> if
    // there is no maximum. Currently only available on the Dev channel.-->
    // 获取窗口当前的最大宽度，如果没有最小值则返回 <code>null</code>。目前仅在 Dev 分支中可用。
    [nocompile] static long getMaxWidth();

    // <!--@Get the current maximum height of the window. Returns <code>null</code>
    // if there is no maximum. Currently only available on the Dev channel.-->
    // 获取窗口当前的最大高度，如果没有最小值则返回 <code>null</code>。目前仅在 Dev 分支中可用。
    [nocompile] static long getMaxHeight();

    // <!--@Set the current minimum width of the window. Set to <code>null</code> to
    // remove the constraint. Currently only available on the Dev channel.-->
    // 设置窗口当前的最小宽度，设置为 <code>null</code> 取消这一约束。目前仅在 Dev 分支中可用。
    static void setMinWidth(optional long minWidth);

    // <!--@Set the current minimum height of the window. Set to <code>null</code> to
    // remove the constraint. Currently only available on the Dev channel.-->
    // 设置窗口当前的最小高度，设置为 <code>null</code> 取消这一约束。目前仅在 Dev 分支中可用。
    static void setMinHeight(optional long minHeight);

    // <!--@Set the current maximum width of the window. Set to <code>null</code> to
    // remove the constraint. Currently only available on the Dev channel.-->
    // 设置窗口当前的最大宽度，设置为 <code>null</code> 取消这一约束。目前仅在 Dev 分支中可用。
    static void setMaxWidth(optional long maxWidth);

    // <!--@Set the current maximum height of the window. Set to <code>null</code> to
    // remove the constraint. Currently only available on the Dev channel.-->
    // 设置窗口当前的最大高度，设置为 <code>null</code> 取消这一约束。目前仅在 Dev 分支中可用。
    static void setMaxHeight(optional long maxHeight);

    // Set the app icon for the window (experimental).
    // Currently this is only being implemented on Ash.
    // TODO(stevenjb): Investigate implementing this on Windows and OSX.
    [nodoc] static void setIcon(DOMString iconUrl);

    // <!--@Set a badge icon for the window.
    // TODO(benwells): Document this properly before going to stable.-->
    // 设置窗口的徽章图标。
    [nodoc] static void setBadgeIcon(DOMString iconUrl);

    // <!--@Clear the current for the window.
    // TODO(benwells): Document this properly before going to stable.-->
    // 清除窗口当前的徽章。
    [nodoc] static void clearBadge();

    // <!--@Is the window always on top?-->
    // 窗口是否前端显示。
    static boolean isAlwaysOnTop();

    // Accessors for testing.
    [nodoc] boolean hasFrameColor;
    [nodoc] long frameColor;

    // <!--@Set whether the window should stay above most other windows. Requires the
    // <code>"alwaysOnTopWindows"</code> permission.-->
    // 设置窗口是否应该前端显示。需要 <code>"alwaysOnTopWindows"</code>
    // 权限。
    static void setAlwaysOnTop(boolean alwaysOnTop);

    // <!--@The JavaScript 'window' object for the created child.-->
    // 已创建子窗口的 JavaScript window 对象。
    [instanceOf=Window] object contentWindow;

    // <!--@The id the window was created with.-->
    // 创建窗口时指定的标识符。
    DOMString id;

    // <!--@The position, size and constraints of the window's content, which does
    // not include window decorations.
    // Currently only available on the Dev channel from Chrome 35.-->
    // 窗口内容的位置、大小和约束，不包括窗口边框。目前仅在 Chrome 35 Dev
    // 分支及更高版本中可用。
    Bounds innerBounds;

    // <!--@The position, size and constraints of the window, which includes window
    // decorations, such as the title bar and frame.
    // Currently only available on the Dev channel from Chrome 35.-->
    // 窗口的位置、大小和约束，包括窗口标题栏和边框。目前仅在 Chrome 35 Dev
    // 分支及更高版本中可用。
    Bounds outerBounds;
  };

  interface Functions {
    // <!--@The size and position of a window can be specified in a number of
    // different ways. The most simple option is not specifying anything at
    // all, in which case a default size and platform dependent position will
    // be used.-->
    // 窗口的大小与位置可以以几种不同的方式指定。最简单的选择是什么都不指定，这种情况下会使用默认大小与平台相关的位置。
    //
    // <!--@Another option is to use the <code>bounds</code> property, which will put
    // the window at the specified coordinates with the specified size. If the
    // window has a frame, it's total size will be the size given plus the size
    // of the frame; that is, the size in bounds is the content size, not the
    // window size.-->
    // 另一种选择是使用 <code>bounds</code>
    // 属性，这样窗口总是会放在指定位置并且具有指定大小。如果窗口有边框，它的总大小是指定大小加上边框的大小。也就是说，bounds
    // 中的大小是内容大小，而不是窗口大小。
    //
    // <!--@To automatically remember the positions of windows you can give them ids.
    // If a window has an id, This id is used to remember the size and position
    // of the window whenever it is moved or resized. This size and position is
    // then used instead of the specified bounds on subsequent opening of a
    // window with the same id. If you need to open a window with an id at a
    // location other than the remembered default, you can create it hidden,
    // move it to the desired location, then show it.-->
    // 如果要自动记录窗口的位置，您可以为它们提供标识符。如果窗口有标识符，该标识符将在窗口移动或调整大小时用于记录它的大小和位置。以后打开具有同样标识符的窗口时使用这一大小和位置，而不是指定的大小和位置。如果您需要打开一个具有标识符的窗口，并且使用不同于记录的默认位置，您可以使它创建时隐藏，将它移动到期望的位置，然后显示它。
    static void create(DOMString url,
                       optional CreateWindowOptions options,
                       optional CreateWindowCallback callback);

    // <!--@Returns an $ref:AppWindow object for the
    // current script context (ie JavaScript 'window' object). This can also be
    // called on a handle to a script context for another page, for example:
    // otherWindow.chrome.app.window.current().-->
    // 返回当前脚本上下文（即 JavaScript window 对象）的
    // $ref:AppWindow 对象。这也可以在另一个页面的脚本上下文句柄上调用，例如
    // otherWindow.chrome.app.window.current()。
    [nocompile] static AppWindow current();
    [nocompile, nodoc] static void initializeAppWindow(object state);

    // <!--@Gets an array of all currently created app windows. This method is new in
    // Chrome 33.-->
    // 获取所有当前创建的应用窗口数组。该方法在 Chrome 33 中新增。
    [nocompile] static AppWindow[] getAll();

    // <!--@Gets an $ref:AppWindow with the given id. If no window with the given id
    // exists null is returned. This method is new in Chrome 33.-->
    // 获取指定标识符的 $ref:AppWindow 对象，如果没有指定标识符的窗口则返回
    // null。该方法在 Chrome 33 中新增。
    [nocompile] static AppWindow get(DOMString id);
  };

  interface Events {
    // <!--@Fired when the window is resized.-->
    // 当窗口改变大小时产生。
    [nocompile] static void onBoundsChanged();

    // <!--@Fired when the window is closed.-->
    // 当窗口关闭时产生。
    [nocompile] static void onClosed();

    // <!--@Fired when the window is fullscreened.-->
    // 窗口全屏时产生。
    [nocompile] static void onFullscreened();

    // <!--@Fired when the window is maximized.-->
    // 当窗口最大化时产生。
    // Fired when the window is maximized.
    [nocompile] static void onMaximized();

    // <!--@Fired when the window is minimized.-->
    // 当窗口最小化时产生。
    [nocompile] static void onMinimized();

    // <!--@Fired when the window is restored from being minimized or maximized.-->
    // 当窗口从最小化或最大化的状态恢复时产生。
    [nocompile] static void onRestored();
  };
};
