// Copyright 2013 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// <!--@Desktop Capture API that can be used to capture content of screen or
// individual windows or tabs.-->
// 桌面捕获 API 可以用于捕获屏幕、单个窗口或标签页的内容。
namespace desktopCapture {
  // <!--@Enum used to define set of desktop media sources used in
  // chooseDesktopMedia().-->
  // 在 chooseDesktopMedia() 中使用，定义桌面媒体来源。
  enum DesktopCaptureSourceType {
    screen,
    window,
    tab
  };

  // |streamId|: <!--@An opaque string that can be passed to
  // <code>getUserMedia()</code> API to generate media stream that corresponds
  // to the source selected by the user. If user didn't select any source
  // (i.e. canceled the prompt) then the callback is called with an empty
  // <code>streamId</code>.-->
  // 不透明字符串，可以传递给 <code>getUserMedia()</code>
  // API，生成与用户选择的源相对应的媒体流。如果用户没有选择任何源（即取消提示），调用回调函数时传递空的
  // <code>streamId</code>。
  callback ChooseDesktopMediaCallback = void (DOMString streamId);

  interface Functions {
    // <!--@Shows desktop media picker UI with the specified set of sources. Returns
    // an id that can be passed to cancelChooseDesktopMedia() in case the prompt
    // need to be canceled.-->
    // 显示桌面媒体选择器用户界面，包含指定类型的源。返回一个可以传递给
    // cancelChooseDesktopMedia() 的标识符，以便在需要时取消提示。
    //
    // |sources|: <!--@Set of sources that should be shown to the user.-->
    // 要向用户显示的源类型。
    //
    // |origin|: <!--@Optional origin of the page for which the stream is created. If
    // not specified then the resulting stream can be used only the calling
    // extension, otherwise the stream can be used only by a page with the
    // specified origin.-->
    // 创建流媒体的网页来源（可选），如果不指定的话，得到的流媒体只能在当前扩展程序中使用，否则只能在指定来源的网页中使用。
    static long chooseDesktopMedia(DesktopCaptureSourceType[] sources,
                                   optional DOMString origin,
                                   ChooseDesktopMediaCallback callback);

    // <!--@Hides desktop media picker dialog shown by chooseDesktopMedia().-->
    // 隐藏由 chooseDesktopMedia() 显示的媒体选择器对话框。
    //
    // |desktopMediaRequestId|: Id returned by chooseDesktopMedia()
    static void cancelChooseDesktopMedia(long desktopMediaRequestId);
  };
};
